pipeline {
  agent any

  environment {
    REGISTRY = "localhost:8082"   // or your VM IP
    REPO = "docker-hosted"
    IMAGE = "my-app"
  }

  stages {

    stage('Build Image') {
      steps {
        dir('multi-stage-multi-agent') {
          sh 'docker build -t $IMAGE .'
        }
      }
    }

    stage('Login to Nexus') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'nexus-deploy-creds',
          usernameVariable: 'USER',
          passwordVariable: 'PASS'
        )]) {
          sh '''
          echo $PASS | docker login $REGISTRY -u $USER --password-stdin
          '''
        }
      }
    }

    stage('Tag Image') {
      steps {
        sh 'docker tag $IMAGE $REGISTRY/$IMAGE:latest'
      }
    }

    stage('Push to Nexus') {
      steps {
        sh 'docker push $REGISTRY/$IMAGE:latest'
      }
    }
  }
}
